### ISSUE TITLE
CSRF cookie fail

### ISSUE THREAD

**Issue by guttersnipe098** [damoti/osedev#7]
I cannot submit my time for last week (10 hours) due to the following error:

Forbidden (403)

CSRF verification failed. Request aborted.

You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.

If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for 'same-origin' requests.

More information is available with DEBUG=True.

**Comment by guttersnipe098** [comment]
![timebookingfail](https://user-images.githubusercontent.com/1097004/30295814-f2d42baa-970f-11e7-9898-b11fb2effd16.png)

**Comment by eukreign** [comment]
The error you got is very common if you hit the back button after submitting a form (or some other strange state related issue occurs). CSRF verfication prevents a lot of client side security problems.

I was able to submit 10 hours for your without any issues by going to your wiki log page and entering 10 for the hours and hitting save.

If you ever get this error again it's best to refresh the page and try again.

If you want more details about what causes this and how it works: 

https://www.squarefree.com/securitytips/web-developers.html#CSRF

https://docs.djangoproject.com/en/dev/ref/csrf/#how-it-works

Let me know if you want me to edit your log and enter something other than "test" for the log entry (or you can log-in to osedev.org and edit it yourself).
