### ISSUE TITLE
allow time submissions for 7 days back

### ISSUE THREAD

**Issue by guttersnipe098** [damoti/osedev#8]
My normal workflow is to submit my last week's time on Monday. Today (Monday Sept 11) I went to book my time for last week, which was done on last Monday Sept 04, but I was only presented with the option to book between Sept 05 - Sept 11.

Expected behaviour is to have the drop-down menu include 7 days back. If today is a Monday, I should be able to book time for the Monday of last week.

**Comment by eukreign** [comment]
Fix deployed to production.
