### ISSUE TITLE
Log entry order temporarily incorrect on Main list

### ISSUE THREAD

**Issue by Witz0** [damoti/osedev#9]
On the https://osedev.org/ Main page in the log entry list I noticed my log entries do not always appear ordered with the newest at the top. When I submit a second entry the same day the first entry appears above the newer one. Specifically, it appears out of order the day of submission and then appears correct the next day. I double checked the order of the list and my log and It is self-correcting after a time though so probably not a priority bug.

**Comment by eukreign** [comment]
fixed in https://github.com/damoti/osedev/commit/536ed1c3049d85c668da12023c90bf8624eadf4a
